#****   LOGGING  ****
#
# Настройки логирования.
#
# msgTypeName - тип сообщения, от этого зависит в какой лог-файл будет отправлятся
#  сообщение, а также с каким префиксом оно будет дублироватся в консоль
# writingFile - нужно ли записывать сообщение в файл или только выводить в консоль
# writingStdout - нужно ли выводить сообщение в консоль
# pathDirectory - директория для записи лог-файлов
# maxFileSize - максимальный размер файла, после которого будет создаваться новый
#  файл, а текущий будет архивироваться
LOGGING:
  - msgTypeName: error
    writingDB: true
    writingStdout: true
    writingFile: true
    pathDirectory: logs
    maxFileSize: 10000000
  - msgTypeName: warning
    writingDB: true
    writingStdout: true
    writingFile: true
    pathDirectory: logs
    maxFileSize: 10000000
  - msgTypeName: info
    writingDB: true
    writingStdout: true
    writingFile: true
    pathDirectory: logs
    maxFileSize: 10000000
